services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: portfolio.onrender.com
    autoDeploy: true
    build:
      pythonVersion: 3.12

    buildCommand: bash render-build.sh && pip install -r requirements.txt
    buildFilter:
      paths:
        - ./
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
