# Generated by Django 4.2.23 on 2025-06-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Higher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='userimage/')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('higher_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portfolio.higher')),
                ('inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portfolio.inter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portfolio.school')),
            ],
        ),
    ]
