# Generated by Django 4.2.23 on 2025-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higher',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='higher',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inter',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inter',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='start',
            field=models.DateField(),
        ),
    ]
