# Generated by Django 4.2.23 on 2025-06-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0003_language_projects_skills_portfolio_hobbies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='ssname',
        ),
    ]
