# Generated by Django 4.2.23 on 2025-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0004_rename_name_skills_ssname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pdesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
