# Generated by Django 4.2.23 on 2025-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0005_alter_projects_pdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
