# Generated by Django 4.2.23 on 2025-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0007_portfolio_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='resume',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkidin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
